import localFont from "next/font/local";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import Nav from "@/components/Nav/nav";
import App_Context from "@/store/App_Context";
import Client_Component from "@/components/Client_Component";
// import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "@/components/ui/sonner";
import { SessionProviderComponent } from "@/components/provider/nextAuthSessionProvider";


const geistSans = localFont({
  src: "../public/fonts/Geist-Regular.ttf",
  variable: "--font-geist-sans",
  weight: "400",
});

const geistMono = localFont({
  src: "../public/fonts/GeistMono-Regular.ttf",
  variable: "--font-geist-mono",
  weight: "400",
});

const orbit = localFont({
  src: "../public/fonts/Orbitron-Regular.ttf",
  variable: "--font-orbit",
  weight: "400",
});

const robotoMono = localFont({
  src: "../public/fonts/RobotoMono-Regular.ttf",
  variable: "--font-roboto-mono",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // let context = useContext(appContext);
  // console.log(context);

  return (
    <html lang="en" className="dark">
      <body
        className={`relative w-full h-full ${geistSans.variable} ${geistMono.variable} ${orbit.variable} ${robotoMono.variable} antialiased bg-background-color`}
      >
        {/* <GoogleOAuthProvider clientId={`${process.env.NEXT_GOOGLE_CLIENT_ID}`}> */}
        <SessionProviderComponent>
          <Client_Component>
            <header className="w-full h-[70px] flex items-center justify-center">
              <Nav />
            </header>
            {children}
            <Toaster richColors position="top-right" offset={85} />
          </Client_Component>
        </SessionProviderComponent>
      </body>
    </html>
  );
}
